namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;

    public partial class Cuestionario01
    {
       
        public System.String COD_ESTABLECIMIENTO { get; set; }
        public System.Int32 P1A { get; set; }
        public System.String P1B { get; set; }
        public System.String DEPARTAMENTO { get; set; }
        public System.String PROVINCIA { get; set; }
        public System.String DISTRITO { get; set; }
        public System.String P1_1 { get; set; }
        public System.String P1_2 { get; set; }
        public System.String P1_3_1 { get; set; }
        public System.String P1_3_2 { get; set; }
        public System.String P1_3_3 { get; set; }
        public System.String P1_4_1 { get; set; }
        public System.String P1_4_2 { get; set; }
        public System.String P1_5 { get; set; }
        public System.String P1_6 { get; set; }
        public System.Int32 P1_8 { get; set; }
        public System.Int32 P1_9 { get; set; }
        public System.String P1_10 { get; set; }
        public System.Int32 P1_11 { get; set; }
        public System.Int32 P1_12 { get; set; }
        public System.Int32 P1_13 { get; set; }
        public System.String P1_13_O { get; set; }
        public System.Int32 P1_14 { get; set; }
        public System.Int32 P2_1_1 { get; set; }
        public System.Int32 P2_1_2 { get; set; }
        public System.Int32 P2_1_3 { get; set; }
        public System.Int32 P2_1_4 { get; set; }
        public System.Int32 P2_1_5 { get; set; }
        public System.Int32 P2_1_6 { get; set; }
        public System.Int32 P2_1_7 { get; set; }
        public System.Int32 P2_1_8 { get; set; }
        public System.Int32 P2_1_9 { get; set; }
        public System.Int32 P2_1_10 { get; set; }
        public System.Int32 P3_1_1 { get; set; }
        public System.Int32 P3_1_2 { get; set; }
        public System.Int32 P3_1_3 { get; set; }
        public System.Int32 P3_1_4 { get; set; }
        public System.Int32 P3_1_5 { get; set; }
        public System.Int32 P3_1_6 { get; set; }
        public System.Int32 P3_1_7 { get; set; }
        public System.Int32 P3_1_8 { get; set; }
        public System.Int32 P3_1_9 { get; set; }
        public System.Int32 P3_1_10 { get; set; }
        public System.Int32 P3_1_11 { get; set; }
        public System.Int32 P3_1_12 { get; set; }
        public System.Int32 P3_1_13 { get; set; }
        public System.Int32 P3_1_14 { get; set; }
        public System.Int32 P3_1_15 { get; set; }
        public System.Int32 P3_1_16 { get; set; }
        public System.Int32 P3_1_17 { get; set; }
        public System.Int32 P3_1_18 { get; set; }
        public System.String P3_1_18_O { get; set; }
        public System.Int32 P3_2 { get; set; }
        public System.Int32 P3_3_1 { get; set; }
        public System.Int32 P3_3_2 { get; set; }
        public System.Int32 P3_3_3 { get; set; }
        public System.Int32 P3_3_4 { get; set; }
        public System.Int32 P3_3_5 { get; set; }
        public System.Int32 P3_3_6 { get; set; }
        public System.Int32 P3_3_7 { get; set; }
        public System.Int32 P3_3_8 { get; set; }
        public System.Int32 P3_3_9 { get; set; }
        public System.Int32 P3_3_10 { get; set; }
        public System.Int32 P3_3_11 { get; set; }
        public System.Int32 P3_3_12 { get; set; }
        public System.Int32 P3_3_13 { get; set; }
        public System.Int32 P3_3_14 { get; set; }
        public System.Int32 P3_3_15 { get; set; }
        public System.Int32 P3_3_16 { get; set; }
        public System.String P3_3_16_O { get; set; }
        public System.Int32 P3_4_1 { get; set; }
        public System.Int32 P3_4_2 { get; set; }
        public System.Int32 P3_4_3 { get; set; }
        public System.Int32 P3_4_4 { get; set; }
        public System.Int32 P3_4_5 { get; set; }
        public System.Int32 P3_4_6 { get; set; }
        public System.Int32 P3_4_7 { get; set; }
        public System.Int32 P3_4_8 { get; set; }
        public System.Int32 P3_4_9 { get; set; }
        public System.Int32 P3_4_10 { get; set; }
        public System.String P3_4_10_O { get; set; }
        public System.Int32 P3_4_11 { get; set; }
        public System.Int32 P3_4_12 { get; set; }
        public System.Int32 P3_5 { get; set; }
        public System.Int32 P3_6_1 { get; set; }
        public System.Int32 P3_6_2 { get; set; }
        public System.Int32 P3_6_3 { get; set; }
        public System.Int32 P3_6_4 { get; set; }
        public System.Int32 P3_6_5 { get; set; }
        public System.Int32 P3_6_6 { get; set; }
        public System.Int32 P3_6_7 { get; set; }
        public System.Int32 P3_6_8 { get; set; }
        public System.Int32 P3_6_9 { get; set; }
        public System.Int32 P3_6_10 { get; set; }
        public System.Int32 P3_6_11 { get; set; }
        public System.Int32 P3_6_12 { get; set; }
        public System.Int32 P3_6_13 { get; set; }
        public System.Int32 P3_6_14 { get; set; }
        public System.Int32 P3_6_15 { get; set; }
        public System.String P3_6_15_O { get; set; }
        public System.Int32 P3_6A { get; set; }
        public System.String P3_7 { get; set; }
        public System.String P3_7_1 { get; set; }
        public System.String P3_8 { get; set; }
        public System.Int32 P4_1 { get; set; }
        public System.Int32 P4_2 { get; set; }
        public System.Int32 P4_3 { get; set; }
        public System.Int32 P4_4_1 { get; set; }
        public System.Int32 P4_4_2 { get; set; }
        public System.Int32 P4_4_3 { get; set; }
        public System.Int32 P4_4_4 { get; set; }
        public System.Int32 P4_4_5 { get; set; }
        public System.Int32 P4_4_6 { get; set; }
        public System.Int32 P4_4_7 { get; set; }
        public System.Int32 P4_4_8 { get; set; }
        public System.String P4_4_8_O { get; set; }
        public System.Int32 P5_1 { get; set; }
        public System.Int32 P5_2 { get; set; }
        public System.Int32 P5_3_1 { get; set; }
        public System.Int32 P5_3_2 { get; set; }
        public System.Int32 P5_3_3 { get; set; }
        public System.Int32 P5_3_4 { get; set; }
        public System.Int32 P5_3_5 { get; set; }
        public System.Int32 P5_3_6 { get; set; }
        public System.Int32 P5_3_7 { get; set; }
        public System.Int32 P5_3_8 { get; set; }
        public System.Int32 P5_3_9 { get; set; }
        public System.String P5_3_9_O { get; set; }
        public System.Int32 P5_4 { get; set; }
        public System.Int32 P5_5_1 { get; set; }
        public System.Int32 P5_5_2 { get; set; }
        public System.Int32 P5_5_3 { get; set; }
        public System.Int32 P5_5_4 { get; set; }
        public System.Int32 P5_5_5 { get; set; }
        public System.Int32 P5_5_6 { get; set; }
        public System.Int32 P5_5_7 { get; set; }
        public System.Int32 P5_5_8 { get; set; }
        public System.Int32 P5_5_9 { get; set; }
        public System.Int32 P5_5_10 { get; set; }
        public System.String P5_5_10_O { get; set; }
        public System.Int32 P6_1 { get; set; }
        public System.Int32 P6_2 { get; set; }
        public System.Int32 P6_3_1 { get; set; }
        public System.Int32 P6_3_2 { get; set; }
        public System.Int32 P6_3_3 { get; set; }
        public System.Int32 P6_3_4 { get; set; }
        public System.Int32 P6_3_5 { get; set; }
        public System.Int32 P6_3_6 { get; set; }
        public System.Int32 P6_4 { get; set; }
        public System.Int32 P6_5 { get; set; }
        public System.Int32 P6_6_1 { get; set; }
        public System.Int32 P6_6_2 { get; set; }
        public System.Int32 P6_6_3 { get; set; }
        public System.Int32 P6_6_4 { get; set; }
        public System.Int32 P6_6_5 { get; set; }
        public System.Int32 P6_6_6 { get; set; }
        public System.Int32 P6_6_7 { get; set; }
        public System.Int32 P6_6_8 { get; set; }
        public System.String P6_6_8_O { get; set; }
        public System.Int32 P6_7_1 { get; set; }
        public System.Int32 P6_7_2 { get; set; }
        public System.Int32 P6_7_3 { get; set; }
        public System.Int32 P6_7_4 { get; set; }
        public System.Int32 P6_7_5 { get; set; }
        public System.Int32 P7_1 { get; set; }
        public System.String P7_2 { get; set; }
        public System.String P7_3 { get; set; }
        public System.Int32 P7_4 { get; set; }
        public System.String P7_4_O { get; set; }

        public System.String USUARIO { get; set; }

    }
}
