//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComunityEntities : DbContext
    {
        public ComunityEntities()
            : base("name=ComunityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_05_DIG_CAP200> T_05_DIG_CAP200 { get; set; }
        public DbSet<T_05_DIG_CONFI> T_05_DIG_CONFI { get; set; }
        public DbSet<T_05_DIG_HOGAR> T_05_DIG_HOGAR { get; set; }
        public DbSet<T_05_DIG_VISITA> T_05_DIG_VISITA { get; set; }
        public DbSet<T_05_DIG_VIVIENDA> T_05_DIG_VIVIENDA { get; set; }
        public DbSet<T_MARCO> T_MARCO { get; set; }
        public DbSet<T_SEGMENTACION> T_SEGMENTACION { get; set; }
    }
}
