//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_05_DIG_VISITA
    {
        public string ID { get; set; }
        public int NROHOGAR { get; set; }
        public int NROVIS { get; set; }
        public Nullable<int> EMODO { get; set; }
        public string EFECHA { get; set; }
        public string EHORADE { get; set; }
        public string EHORAA { get; set; }
        public string EPVFECHA { get; set; }
        public string EPVHORA { get; set; }
        public Nullable<int> ERESVIS { get; set; }
        public string ERESVIS_O { get; set; }
        public string SFECHA { get; set; }
        public string SHORADE { get; set; }
        public string SHORAA { get; set; }
        public Nullable<int> SRESVIS { get; set; }
        public string SRESVIS_O { get; set; }
        public string GPSLATITUDE { get; set; }
        public string GPSLONGITUDE { get; set; }
        public string GPSTIME { get; set; }
        public string GPSSPEED { get; set; }
        public string GPSACCURACY { get; set; }
        public string GPSALTITUDE { get; set; }
        public string GPSBEARING { get; set; }
        public string USUCRE { get; set; }
        public string FECCRE { get; set; }
        public string USUREG { get; set; }
        public string FECREG { get; set; }
        public string FECENV { get; set; }
        public string ERESVIS_O2 { get; set; }
    }
}
