//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_05_DIG_HOGAR
    {
        public string ID { get; set; }
        public int P8 { get; set; }
        public string P12_1 { get; set; }
        public Nullable<int> P12_2 { get; set; }
        public string P12_2_O { get; set; }
        public Nullable<int> P14 { get; set; }
        public Nullable<int> P15 { get; set; }
        public Nullable<int> P198 { get; set; }
        public Nullable<int> P199 { get; set; }
        public string OBS_CARATULA { get; set; }
        public Nullable<int> P100_INF { get; set; }
        public string OBS_CAP100 { get; set; }
        public string USUCRE { get; set; }
        public string FECCRE { get; set; }
        public string USUREG { get; set; }
        public string FECREG { get; set; }
        public string FECENV { get; set; }
        public Nullable<int> M101 { get; set; }
        public Nullable<int> M102 { get; set; }
        public Nullable<int> P100_INFM { get; set; }
        public string OBS_CAP100M { get; set; }
        public Nullable<int> P113_1 { get; set; }
        public Nullable<int> P113_2 { get; set; }
        public Nullable<int> P113_3 { get; set; }
        public Nullable<int> P113_4 { get; set; }
        public Nullable<int> P113_5 { get; set; }
        public Nullable<int> P113_6 { get; set; }
        public Nullable<int> P113_7 { get; set; }
        public Nullable<int> P113_8 { get; set; }
        public Nullable<int> P114_1 { get; set; }
        public Nullable<int> P114_2 { get; set; }
        public Nullable<int> P114_3 { get; set; }
        public Nullable<int> P114_4 { get; set; }
        public string P114_4E { get; set; }
        public Nullable<int> P114_5 { get; set; }
        public Nullable<int> digita1 { get; set; }
        public string digit { get; set; }
        public Nullable<int> flag_ree { get; set; }
        public Nullable<int> p12r { get; set; }
        public string P113_7E { get; set; }
        public Nullable<int> P12BE2 { get; set; }
        public string usurecu { get; set; }
    
        public virtual T_05_DIG_VIVIENDA T_05_DIG_VIVIENDA { get; set; }
    }
}
