//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_05_DIG_CONFI
    {
        public string ID { get; set; }
        public int NROHOGAR { get; set; }
        public int NROPERSONA { get; set; }
        public Nullable<int> PH223 { get; set; }
        public string PH223_O { get; set; }
        public Nullable<int> PH224 { get; set; }
        public Nullable<int> PH225 { get; set; }
        public Nullable<int> PH204A { get; set; }
        public Nullable<int> PH205A { get; set; }
        public Nullable<int> PH206 { get; set; }
        public Nullable<int> PH209A { get; set; }
        public Nullable<int> PH211 { get; set; }
        public Nullable<int> PHOTR { get; set; }
        public string HOTRO { get; set; }
        public string HOBS { get; set; }
        public Nullable<int> FLGTERHC { get; set; }
        public string USUCRE { get; set; }
        public string FECCRE { get; set; }
        public string USUREG { get; set; }
        public string FECREG { get; set; }
        public string FECENV { get; set; }
        public string C_FECDIG { get; set; }
    }
}
