//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SEGMENTACION
    {
        public int ID { get; set; }
        public string COD_SEDE_OPERATIVA { get; set; }
        public string SEDE_OPERATIVA { get; set; }
        public string CCDD { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string CCPP { get; set; }
        public string PROVINCIA { get; set; }
        public string CCDI { get; set; }
        public string DISTRITO { get; set; }
        public string UBIGEO { get; set; }
        public string JEFE_EQUIPO { get; set; }
        public string EQUIPO { get; set; }
        public string RUTA { get; set; }
        public string COD_SUPNAC { get; set; }
        public string COD_COR { get; set; }
        public string COD_JEF { get; set; }
        public string COD_SUPERVISOR { get; set; }
        public string COD_ENCUESTADOR { get; set; }
        public string COD_ENCUESTADOR_2 { get; set; }
        public string PERIODO { get; set; }
        public string CONGLOMERADO { get; set; }
        public string SUBMUESTRA { get; set; }
        public string ANIO { get; set; }
        public string MES { get; set; }
        public string PANEL { get; set; }
        public string ESTRATO { get; set; }
        public string USUCRE { get; set; }
        public string FECCRE { get; set; }
        public string USUREG { get; set; }
        public string FECREG { get; set; }
        public string FECENV { get; set; }
        public string COD_ANALISTA { get; set; }
    }
}
