//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EPE_2020_3Entities : DbContext
    {
        public EPE_2020_3Entities()
            : base("name=EPE_2020_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_05_DIG_CAP100> T_05_DIG_CAP100 { get; set; }
    
        public virtual ObjectResult<LISTADO_PERSONAS_WEB_Result> LISTADO_PERSONAS_WEB(string iD, Nullable<int> nROHOGAR)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var nROHOGARParameter = nROHOGAR.HasValue ?
                new ObjectParameter("NROHOGAR", nROHOGAR) :
                new ObjectParameter("NROHOGAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTADO_PERSONAS_WEB_Result>("LISTADO_PERSONAS_WEB", iDParameter, nROHOGARParameter);
        }
    }
}
