//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_05_DIG_CAP100
    {
        public string ID { get; set; }
        public int NROHOGAR { get; set; }
        public int P101 { get; set; }
        public string P101P { get; set; }
        public string P102_1 { get; set; }
        public string P102_2 { get; set; }
        public Nullable<int> P103 { get; set; }
        public Nullable<int> P104 { get; set; }
        public Nullable<int> P105 { get; set; }
        public Nullable<int> P106 { get; set; }
        public Nullable<int> P107 { get; set; }
        public Nullable<int> P108 { get; set; }
        public string P108_OBS { get; set; }
        public Nullable<int> P109_1 { get; set; }
        public Nullable<int> P109_2 { get; set; }
        public Nullable<int> P109_3 { get; set; }
        public string P110A { get; set; }
        public string P111 { get; set; }
        public string P112 { get; set; }
        public string OBS { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string USUCRE { get; set; }
        public string FECCRE { get; set; }
        public string USUREG { get; set; }
        public string FECREG { get; set; }
        public string FECENV { get; set; }
        public string P110A_1 { get; set; }
        public string P110A_2 { get; set; }
        public Nullable<int> P110A_3 { get; set; }
        public string P110B_1 { get; set; }
        public string P110B_2 { get; set; }
        public Nullable<int> P110B_3 { get; set; }
        public Nullable<int> P110B_4 { get; set; }
        public Nullable<int> P113 { get; set; }
        public Nullable<int> P114 { get; set; }
        public Nullable<int> P115 { get; set; }
        public string P115_O { get; set; }
        public Nullable<int> FLAG { get; set; }
        public Nullable<int> FLAG_ADD { get; set; }
        public string usurecu { get; set; }
    }
}
